// @event-horizon/opencode-plugin
// Auto-generated by Event Horizon VS Code extension.
// Forwards OpenCode events to the Event Horizon visualization server.
// Do not edit — reinstall from Event Horizon's Connect panel.

const PORT = 28765;
const AUTH_TOKEN = process.env.EVENT_HORIZON_AUTH_TOKEN || "";
const AUTH_HEADERS = AUTH_TOKEN
  ? { "Content-Type": "application/json", "Authorization": "Bearer " + AUTH_TOKEN }
  : { "Content-Type": "application/json" };

function send(eventName, extra) {
  const body = JSON.stringify({ event: eventName, ...extra });
  fetch("http://127.0.0.1:" + PORT + "/opencode", {
    method: "POST",
    headers: AUTH_HEADERS,
    body,
  }).catch(() => {});
}

async function checkLock(filePath, agentId, agentName) {
  try {
    const resp = await fetch("http://127.0.0.1:" + PORT + "/lock", {
      method: "POST",
      headers: AUTH_HEADERS,
      body: JSON.stringify({ action: "check", filePath, agentId, agentName }),
      signal: AbortSignal.timeout(2000),
    });
    if (resp.status === 409) {
      const data = await resp.json();
      throw new Error("[Event Horizon file lock] BLOCKED: " + filePath + " is locked by " + (data.owner || "another agent") + " who is actively editing it. You MUST NOT write to this file by ANY means — no Write, no Edit, no Bash echo/cat/sed, no workarounds. The lock will release automatically when they finish (within 30 seconds of their last write). Work on OTHER files first, then retry this file later.");
    }
  } catch (e) {
    if (e && e.message && e.message.includes("is locked by")) throw e;
    // Ignore network errors — Event Horizon might not be running
  }
}

async function releaseLock(filePath, agentId) {
  try {
    await fetch("http://127.0.0.1:" + PORT + "/lock", {
      method: "POST",
      headers: AUTH_HEADERS,
      body: JSON.stringify({ action: "release", filePath, agentId }),
      signal: AbortSignal.timeout(2000),
    });
  } catch {}
}

function sendExit(eventName, extra) {
  send(eventName, extra);
  try {
    const { spawnSync } = require("node:child_process");
    const body = JSON.stringify({ event: eventName, ...extra });
    const headerList = AUTH_TOKEN
      ? "'Content-Type':'application/json','Authorization':'Bearer " + AUTH_TOKEN + "'"
      : "'Content-Type':'application/json'";
    spawnSync("node", ["-e",
      "require('http').request({hostname:'127.0.0.1',port:" + PORT +
      ",path:'/opencode',method:'POST',headers:{" + headerList + "}}" +
      ",()=>process.exit()).end(" + JSON.stringify(body) + ")"
    ], { timeout: 2000, stdio: "ignore" });
  } catch {}
}

export async function EventHorizon(input = {}) {
  const { project, directory, worktree, serverUrl } = input || {};
  // Use project.id when available, but always append a unique suffix so
  // multiple OpenCode instances in the same project get separate planets.
  const base = project?.id ? String(project.id) : "opencode";
  const uid = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const sessionId = base + "-" + uid;

  // Resolve cwd — worktree/directory may be strings, URL objects, or absent.
  // Try every possible source, including process.cwd() as ultimate fallback.
  function resolvePath(v) {
    if (!v) return undefined;
    if (typeof v === "string") return v;
    if (typeof v === "object" && v.href) {
      // file:///C:/path or file:///home/path
      try { return new URL(v.href).pathname.replace(/^\/([A-Z]:)/, "$1"); } catch {}
      return v.href.replace(/^file:\/\/\//, "").replace(/^file:\/\//, "");
    }
    if (typeof v === "object" && v.pathname) return v.pathname;
    return String(v);
  }
  const cwd = resolvePath(worktree)
    || resolvePath(directory)
    || resolvePath(project?.path)
    || resolvePath(project?.directory)
    || resolvePath(project?.worktree)
    || (typeof process !== "undefined" && process.cwd ? process.cwd() : undefined);
  const cwdFolder = cwd ? String(cwd).replace(/\\/g, "/").split("/").pop() : undefined;
  const agentName = cwdFolder ? "OpenCode (" + cwdFolder + ")" : "OpenCode";
  // OpenCode's internal server URL — used by Event Horizon for SSE subagent tracking
  const opencodeServerUrl = typeof serverUrl === "object" && serverUrl?.href ? serverUrl.href : (typeof serverUrl === "string" ? serverUrl : undefined);

  // Send initial session.created
  send("session.created", { sessionId, agentName, cwd, payload: {}, serverUrl: opencodeServerUrl });

  // Continuously re-send session.created as a heartbeat so Event Horizon
  // can discover this agent even if it started after OpenCode.
  // Runs every 30 seconds indefinitely - Event Horizon deduplicates spawns.
  const heartbeatInterval = setInterval(() => {
    send("session.created", { sessionId, agentName, cwd, payload: { heartbeat: true }, serverUrl: opencodeServerUrl });
  }, 30000);

  // Send session.deleted when OpenCode exits (Ctrl+C, exit command, etc.)
  const onExit = () => {
    clearInterval(heartbeatInterval);
    sendExit("session.deleted", { sessionId, agentName, cwd, payload: {} });
  };
  process.on("beforeExit", onExit);
  process.on("SIGINT", () => { onExit(); process.exit(0); });
  process.on("SIGTERM", () => { onExit(); process.exit(0); });

  return {
    event: async ({ event }) => {
      send(event?.type ?? "unknown", {
        sessionId,
        agentName,
        cwd,
        payload: event ?? {},
      });
    },
    "tool.execute.before": async (input) => {
      const toolName = String(input?.tool || "");
      const fp = input?.input?.file_path || input?.input?.path;
      const parentID = input?.sessionID !== input?.parentID ? input?.parentID : undefined;
      send("tool.execute.before", {
        sessionId,
        agentName,
        cwd,
        payload: {
          toolName,
          sessionID: input?.sessionID,
          callID: input?.callID,
          filePath: fp ? String(fp) : undefined,
          parentID,
        },
      });
      // Check file lock for any tool that accesses files
      const toolLower = toolName.toLowerCase();
      const fileTool = ["read", "write", "edit", "patch", "file_read", "file_write", "file_edit"].includes(toolLower);
      if (fileTool && fp) {
        await checkLock(String(fp), sessionId, agentName);
      }
    },
    "tool.execute.after": async (input) => {
      const fp = input?.input?.file_path || input?.input?.path;
      send("tool.execute.after", {
        sessionId,
        agentName,
        cwd,
        payload: {
          toolName: input?.tool,
          sessionID: input?.sessionID,
          callID: input?.callID,
          filePath: fp ? String(fp) : undefined,
        },
      });
      // Locks NOT released here — auto-expire via 30s TTL.
      // Each tool.execute.before refreshes the TTL.
      if (false) { // keep releaseLock available for future use
        const fp = input?.input?.file_path || input?.input?.path;
        if (fp) await releaseLock(String(fp), sessionId);
      }
    },
    "permission.asked": async (input) => {
      send("permission.asked", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, permission: input?.permission },
      });
    },
    "permission.replied": async (input) => {
      send("permission.replied", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, granted: input?.granted },
      });
    },
  };
}

const plugin = {
  id: "event-horizon",
  name: "Event Horizon",
  setup: EventHorizon,
  effect: EventHorizon,
  server: EventHorizon,
};

export default plugin;
